### ISSUE TITLE
Icon change for macOS Big Sur

### ISSUE THREAD

**Issue by ardacebi** [Splode/pomotroid#103]
macOS Big Sur changes all system apps' icons to square ones. Many third party apps such as Adobe are already adopting this new design to their apps. 

Are there any plans for Pomotroid?

<img width="400" alt="Screen Shot 2020-06-25 at 12 16 52" src="https://user-images.githubusercontent.com/17576065/85692078-c194bf00-b6dd-11ea-854b-a7fdcce3f2b6.png">

**Comment by ardacebi** [comment]
## Update
I've made an icon, I'd like some thoughts:
<img src="https://user-images.githubusercontent.com/17576065/85693370-daea3b00-b6de-11ea-89e4-e9d0ca9a8076.png" width=200></img>

**Comment by Splode** [comment]
@ardacebi brilliant! Looks great! Thanks for the contribution. I think that should work nicely.

I'll leave this issue open as a way to track the implementation of the new macOS icon.

**Comment by Splode** [comment]
Implemented in [v0.11.0](https://github.com/Splode/pomotroid/releases/tag/v0.11.0). Thanks again!

**Comment by ardacebi** [comment]
I tested the new implementation on Big Sur, here is what it looks like:

<img width="416" alt="Screen Shot 2020-06-29 at 12 21 55" src="https://user-images.githubusercontent.com/17576065/86037385-fab79100-ba47-11ea-934a-da4dfc72257f.PNG">

If you look closely, there are drop shadows on the system icons. Pomotroid's new icon does not feature any drop shadow.

Is there anything we can do about this?

**Comment by Splode** [comment]
@ardacebi thanks for the update. Is there a source file (AI, PSD) that you can share for the updated icon? I can add a subtle drop shadow.

**Comment by ardacebi** [comment]
@Splode I dropped the file to your email.

**Comment by ardacebi** [comment]
Hey @Splode, Apple published the new icon specifications including the shadow information. I'll be sending my design with the shadow in a few mins to your email.

**Comment by ardacebi** [comment]
Seems like case closed?
