### ISSUE TITLE
Poor feedback from toggle controls in settings

### ISSUE THREAD

**Issue by victorz** [Splode/pomotroid#108]
I'm using Pomotroid 0.11.1, installed from [the AUR package I maintain](https://aur.archlinux.org/packages/pomotroid-bin/).

I see this behavior when toggling the boolean options on and off in the settings view:

![settings](https://user-images.githubusercontent.com/7494/86370239-c29a9300-bc7f-11ea-8835-e53c46a97b7e.gif)

Notice how there is no feedback whatsoever on click. The toggles always look like they are disabled on hover, which is the confusing part I suppose. In the clip above, I click the toggle as soon as I enter it with the mouse pointer.

**Comment by Splode** [comment]
@victorz Thanks for pointing this out. I agree: this could certainly be improved.
