### ISSUE TITLE
about privacy: is there anything to worry about?

### ISSUE THREAD

**Issue by hunkjazz** [Splode/pomotroid#112]
- Does the app collects data from users?
- What kind of information it saves in my computer?

**Comment by Splode** [comment]
> Does the app collects data from users?

We don't collect any data from users; there is no telemetry whatsoever.

> What kind of information it saves in my computer?

User preferences, such as timer lengths, auto-start, etc. are stored in the typical configuration location based on the platform. For example, `%appdata%` on Windows. 14 days worth of timer logs are stored there as well.
