### ISSUE TITLE
[help] how can I install it properly in Fedora 32 Workstation?

### ISSUE THREAD

**Issue by hunkjazz** [Splode/pomotroid#113]
I just extracted `pomotroid-0.11.1-linux.tar.gz` and ran `./pomotroid`.

It works fine. Although, it's not like Windows which move files to a proper folder and creates a shortcut.

Whenever I need to use pomotroid I need to go to it's directory and execute it using terminal.

Would you mind explaning to a noob where to store these files and how to create a shortcut accessible both in terminal and Gnome menu?

I don't mind if you just point how to Google it.

**Comment by maksymsan** [comment]
Desktop files: putting your application in the desktop menus: https://developer.gnome.org/integration-guide/stable/desktop-files.html.en
