### ISSUE TITLE
Ctrl+W closes pomotroid instance

### ISSUE THREAD

**Issue by johnjacobkenny** [Splode/pomotroid#121]
Today I unknowingly pressed `Ctrl+W` when pomotroid was active. I'm on Linux using the AppImage. It closed (as you would expect a browser tab to close).

However for an app like this, I don't think that is an expected behavior? What do you folks think?

If this behavior can/should be changed, I would like to contribute. :smiley:

**Comment by Splode** [comment]
Hi @johnjacobkenny. No, I think you're right: that's not expected behavior.

Any contributions are welcome!

**Comment by johnjacobkenny** [comment]
A quick search brought me to an [SO page](https://stackoverflow.com/questions/60350520/electron-browser-window-prevent-controlw-closing-window). Here are the three options that are suggested, which do you suggest would be optimal?

* `Menu.setApplicationMenu(null)` // would remove default application menu
* `browserWindow.setMenu(null)` // would remove menu for the current window
* `globalShortcut.register("CommandOrControl+W", callback)` // would capture the specific key combo and do nothing

**Comment by Splode** [comment]
@johnjacobkenny,

> Here are the three options that are suggested, which do you suggest would be optimal?

The second option, using the `setMenu` method, is probably the simplest and most straight-forward. We don't use any other default menu items, so removing it shouldn't be an issue.
