### ISSUE TITLE
App not rendering occasionally during development

### ISSUE THREAD

**Issue by johnjacobkenny** [Splode/pomotroid#126]
This has happened a couple of times now during development. I run `npm run dev` and the app is showing up like this. If I stop and rerun, I get the same output. Then I delete `node_modules` and do an `npm i` again. After that if I run it works. I'm on linux. Not sure what is happening in between.

![image](https://user-images.githubusercontent.com/19240564/94095196-d1d44b80-fe3e-11ea-8a93-e0520a8bd9ba.png)

**Comment by Splode** [comment]
I'm not where the issue lies here. This is a screen I'd expect to see if there was a runtime error that caused the frontend not to load properly. I'm curious as to why removing and re-installing dependencies fixes it.
