### ISSUE TITLE
Logo graphics desing 

### ISSUE THREAD

**Issue by Arslanshn** [Splode/pomotroid#13]
Hello  I have Arslanshn need new or improved graphics SteMit.com is a graphic designer I need your approval to be accepted to the project projem Please..

**Comment by Splode** [comment]
I’m not what your question or issue is. Can you please clarify?

**Comment by Arslanshn** [comment]
hi i am graphic designer. What I want to contribute to your project needs the approval of logo designing new bits .the only you, "yes you can contribute to this project for designing a new logo and a beautiful arslanshn" will suffice. I would appreciate any fees or something else if you give consent not said .it's enough. If there is no charge or anything else, it will be cheerful

17 Mar 2018 ÖS 11:59 tarihinde Christopher Murphy <notifications@github.com> yazdı:

I’m not what your question or issue is. Can you please clarify?

**Comment by Splode** [comment]
Thanks, @Arslanshn. I’m not that we need additional design assets or redesigns at this time. However, if you’d like to propose a design, create a pull request with the new assets. 

You may want to take a look at the [Pomotroid site](https://github.com/Splode/pomotroid-site) and suggest some design assets there.
