### ISSUE TITLE
Track pomodoro of others on local network

### ISSUE THREAD

**Issue by Mat-thieu** [Splode/pomotroid#14]
Hi @Splode,

I am currently working on adding a way to discover other pomotroid users on a local network so you can track their timers and set an alarm once their break starts so you can ask them a question without breaking their concentration.

Would this be something you'd be interested in including in this repo? Mind you it ~~does~~ might add about 50mb of dependencies for including local network utilities (Nmap).

**Comment by Splode** [comment]
Hi @mat-thieu, I think that this might be too niche a feature and that too few people would use it to justify the added complexity and size.

I hope to keep Pomotroid relatively lightweight and dead-simple to use. It’s an interesting feature, though, and I’d be interested to see how it impacts the code base. What would a user need to do in order to configure/enable that option?

**Comment by Mat-thieu** [comment]
@Splode 

> I hope to keep Pomotroid relatively lightweight and dead-simple to use. It’s an interesting feature, though, and I’d be interested to see how it impacts the code base. What would a user need to do in order to configure/enable that option?

That makes a lot of sense and it's probably in the best interest of this application to hold on to that. 
I haven't completely worked out the specifics (because local network discovery is quite new to me) but right now it affects the code base by adding a third option to the settings drawer, a new util, a vuex store module and of course os-specific dependencies. 

Furthermore, it would not require the end user to actually install anything at all, the dependencies would be bundled for the specific OS ([Nmap](https://nmap.org/), an ancient piece of software) as a portable, pre-installed dep, hence the size increase of 50mb (but I personally believe this is not a deal breaker for desktop apps).

Configuration would be a single display name, the feature will first try to attempt to find the currently logged-in user's name and else generate something to placehold it. I'm not sure yet if I will be making this feature an opt-in or opt-out, I fear that if I make this opt-in people would have to ask colleagues to turn it on, adding more hassle. The additional drawer view would only be a list of the connected pomotroid instances with a checkbox to alert at their next break.

> I think that this might be too niche a feature and that too few people would use it to justify the added complexity and size.

I kind of agree here, this feature might initially be niche for single developers (remote workers, hobbyists or people like me who want to measure the impact of pomodoro at my work pace). But it would definetly be used within companies that want to make use of pomodoro, it would also drive some developers to suggest the use of pomotroid within their company, meaning this app might become more popular due to word-of-mouth.

**Comment by Splode** [comment]
@Mat-thieu Thanks for the clarification. I'm intrigued by the idea. When you reach a workable milestone in the fork, I'd be happy to take a look at it.

**Comment by Mat-thieu** [comment]
@Splode Which OS are you using? I am fairly certain it's working well on windows (have yet to push it)

**Comment by Splode** [comment]
@Mat-thieu Windows 10 primarily, though I have Ubuntu and Mac setups as well.
