### ISSUE TITLE
I love the simple clean UI of pomotroid, it would be better if a simple to-do list is added

### ISSUE THREAD

**Issue by shaoyongcn** [Splode/pomotroid#15]
To-do list feature
----------------------------------
* Create/Mark done to-do item
* Able to track time spent on a to-do item by placing tomato flags on it
* Keep to-do list history of each day

**Comment by Splode** [comment]
Thanks for the feedback!

I'd like to keep the scope of the app pretty tight, so I'm not sure that it makes sense to add a to-do tracker. Having tracking and history functionality is an interesting idea, though.

Maybe others will chime in, or someone will pick up that feature.

**Comment by paperdigits** [comment]
I completely disagree with this request. There are a bevy of pomodoro timers that includes task lists, but I don't want this feature. I keep my tasks elsewhere. I love this application because it is a timer & that is it.

**Comment by henryjw** [comment]
[Be Focused](https://itunes.apple.com/us/app/be-focused-focus-timer/id973130201) is a good option if you're on a Mac.

**Comment by Atrebas** [comment]
@Splode, having a simple log file, with day / start time / end time / type (work or break) would already be super useful. Users could import the log with an external software, whatever it is (R, Python Excel, ...), to analyze it and keep track of their achievements over time.
Nice app!

**Comment by kaufmann42** [comment]
Just wanted to chime in and say I love the app, but would also appreciate this feature opt-in. Would also help with relaying tasks back to my team daily, etc etc. I understand & appreciate if the project scope is trying to remain narrow.

**Comment by Splode** [comment]
Logging implemented in [v0.10.0](https://github.com/Splode/pomotroid/releases/tag/v0.10.0). This feature addresses the request for logging. I'm closing this issue as the TO-DO list tracking isn't on track to be implemented.
