### ISSUE TITLE
New Logo for Pomotroid

### ISSUE THREAD

**Issue by ariefmunanzar** [Splode/pomotroid#17]
Hi Developer 😊
I'm a graphic designer and i'm willing to design an icon and a logo for your application and i need your permission before start .

**Comment by Splode** [comment]
Hi @ariefmunanzar, thanks for reaching out. I’m not sure that we need additional design assets or redesigns at this time. However, if you’d like to propose a design, create a pull request with the new assets and I'd certainly be willing to consider them.

**Comment by ariefmunanzar** [comment]
Thank for you feedback, sir. I will prepare it in 1 day
