### ISSUE TITLE
Don't automatically start the timer

### ISSUE THREAD

**Issue by mrrcollins** [Splode/pomotroid#18]
Is there an option or a way to not have Pomotroid not automatically start the timer after each interval?

**Comment by Splode** [comment]
This isn't currently a feature, but should be fairly simple to implement. I'll go ahead and add it to the feature roadmap 👍

**Comment by Splode** [comment]
✔ This feature has been implemented with [release v0.3.0](https://github.com/Splode/pomotroid/releases/tag/v0.3.0).
