### ISSUE TITLE
Where can I find the log files?

### ISSUE THREAD

**Issue by longinus13** [Splode/pomotroid#184]
I've seen where to find it for linux on a previous thread before but I'm on windows 10 and not exactly sure where is it. 

Also, I'm not very experienced at coding and all of that but if someone could guide me in the direction to display my log files as graphical information then I'd appreciate that very much.

**Comment by Splode** [comment]
@longinus13 `C:\Users\{UserName}\AppData\Roaming\pomotroid\logs`

Replace `{UserName}` with your current user.
