### ISSUE TITLE
Inquiry about adding extra functions to the notification

### ISSUE THREAD

**Issue by doguma** [Splode/pomotroid#21]
Hi, this isn't actually an issue but I wanted to ask about adding more functions to the notifications.

Is there way to change the position of the notification randomly, as well as making them wait until there's any click?

I couldn't find much clue from "Notification.vue" file, so I checked your package.json, and I found node-notifier, and am still working my way to implementing it.

It's my first time using vue.js, and it will be a big help if you could provide few hints to implementing this. Thank you.

**Comment by Splode** [comment]
Notifications are indeed managed by [`node-notifier`](https://github.com/mikaelbr/node-notifier), which binds native OS notifications. The position of the notification windows is managed by the OS and therefore I don't believe that the position is configurable via `node-notifier`. 

One possible solution is to not use native notifications and instead spawn notifications using new electron [BrowserWindows](https://electronjs.org/docs/api/browser-window). This approach would allow you to programmatically set the position of the window, content and styling, and UI events.

Hope this helps.
