### ISSUE TITLE
GPU process isn't usable. Goodbye.

### ISSUE THREAD

**Issue by Mossy93** [Splode/pomotroid#260]
The app will not launch for me on Arch Linux.

When launching from terminal, I get the following:

`[46429:0306/084023.189706:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
fish: Job 1, 'pomotroid' terminated by signal SIGTRAP (Trace or breakpoint trap)`

**Comment by johnzzon** [comment]
Same for me. Also using Arch linux but with awesomewm as window manager.

```
$ pomotroid
[85097:0307/121902.484358:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
[1]    85097 trace trap (core dumped)  pomotroid
```

**Comment by johnzzon** [comment]
Found another issue on here, that has a solution: https://github.com/Splode/pomotroid/issues/207#issuecomment-1081440325

So simply adding `--disable-gpu-sandbox` to the Exec in the .desktop-file:
```
sudo nano /usr/share/applications/pomotroid.desktop
```
It should then look like this:
```
Exec=/usr/bin/pomotroid --disable-gpu-sandbox
```

**Comment by Mossy93** [comment]
Thank you. That fixed it
