### ISSUE TITLE
Settings partially lost if both timer and view settings are changed

### ISSUE THREAD

**Issue by letmaik** [Splode/pomotroid#27]
Looking at the source code of Timer.js and View.js, both storage modules create a `LocalStore` object where the data is read from a JSON configuration file on disk. Since those objects are independent, changing options from both tabs will loose any changes from the tab that was edited first. E.g. first I change the work timer to 20min, and then I disable desktop notifications. After restarting the app, the work timer change is lost.

**Comment by Splode** [comment]
Fixed with b42e5c2009a9dfe9d65555b167d4e6ca9b519372. Thanks 👍🏼
