### ISSUE TITLE
Error on Arch Linux

### ISSUE THREAD

**Issue by Only1337** [Splode/pomotroid#272]
When I try to open Pomotroid, a rectangle screen in black tones appears on my screen for a short time and then closes.

I get the following output:
```
╭─only@only in ~ via  v3.11.5 as 🧙 took 1m2s
╰─λ pomotroid
[356317:1109/210920.561325:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
fish: Job 1, 'pomotroid' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

My system features are as follows:

```
OS: Garuda Linux x86_64
Kernel: 6.5.9-zen2-1-zen
Packages: 2025 (pacman)
Shell: bash 5.2.15
Resolution: 1920x1080
DE: Plasma 5.27.9
WM: kwin
CPU: Intel i7-8700 (12) @ 4.600GHz
GPU: AMD ATI Radeon RX 580 2048SP
Memory: 5908MiB / 15929MiB
```

**Comment by Edll** [comment]
I have the same problem. It helped me to switch off the minimize to tray in the config and then restart the system once.

**Comment by Only1337** [comment]
```
pomotroid --in-process-gpu
```

When I ran pomotroid with the --in-process-gpu flag, the issue was resolved.

Alternatively, you can use --disable-gpu-sandbox or --no-sandbox.
