### ISSUE TITLE
System notifications when timer expires

### ISSUE THREAD

**Issue by alexandrubau** [Splode/pomotroid#3]
Sometimes I listen to music and the chime sound is not enough, I think some desktop notifications would be nice, or any visual feedback.

**Comment by Splode** [comment]
I agree, this is something I'd like to implement. Adding it to the project roadmap.

**Comment by Mat-thieu** [comment]
+1 I love how simple but good-looking this app is but I've missed the breaks multiple times today, so I can't really continue using the app until notifications are in place.

I suspect using this lib will make it really easy for you:

https://github.com/mikaelbr/node-notifier

**Comment by Splode** [comment]
Thanks for the tip @Mat-thieu. Notifications are currently available in the Master branch via `node-notifier` for Windows, and the the native HTML5 Notifications API for Mac OS and Linux. 

This release will go out soon, but I want to implement the ability to disable notifications via a settings toggle in the app first.

**Comment by Mat-thieu** [comment]
@Splode Sweet, will look forward to it!

**Comment by Splode** [comment]
Notifications added with [v0.2.0](https://github.com/Splode/pomotroid/releases/tag/v0.2.0)
