### ISSUE TITLE
[Feature request] ability to adjust alarm volume

### ISSUE THREAD

**Issue by ilc168** [Splode/pomotroid#34]
It's a gentle alarm sound (on Windows), but regardless I (and my colleagues) would like the ability to adjust its volume.

**thanks for your work. It's my favourite pomodoro timer I've come across.

**Comment by Splode** [comment]
Thanks! Volume control is now available with [v0.6.0](https://github.com/Splode/pomotroid/releases/tag/v0.6.0).
