### ISSUE TITLE
[Feature Request] Prevent accidental closing

### ISSUE THREAD

**Issue by bnjmnfnk** [Splode/pomotroid#36]
Would be nice if there is a notification/confirm when i try to close the app while the time is running

**Comment by mouarfff** [comment]
And have an option "minimize to tray when closing button pressed" :)

**Comment by ivangretsky** [comment]
Yep, "minimize to tray when closing button pressed" would be super useful.

**Comment by Splode** [comment]
Implemented in [v0.11.0](https://github.com/Splode/pomotroid/releases/tag/v0.11.0)
