### ISSUE TITLE
[Suggestion] Portable Application

### ISSUE THREAD

**Issue by raphaelg** [Splode/pomotroid#38]
Hi, 

Thanks for this great project !

It would be great however to have a portable application for those who cannot install anything on 
non-personal (work) computers.

Thanks !

**Comment by Splode** [comment]
Hi and thanks!

Great suggestion. I've added portable versions for Windows and Mac OS with the latest release: https://github.com/Splode/pomotroid/releases/tag/v0.6.1

They may need further testing on machines with restricted user access.

New releases of Pomotroid should ship with portable versions as well.
