### ISSUE TITLE
User experience

### ISSUE THREAD

**Issue by miricknoname** [Splode/pomotroid#4]
1. Can not change **sound volume**, so its quit.
2. Can not **minimize to tray**.
3. Would be awesome to see small **to-do manager** inside this app

**Comment by Splode** [comment]
Thanks for the feedback!
1. Volume control is generally handled by system volume, but it may be worthwhile adding a volume slider to the app. Adding this to the [project board](https://github.com/Splode/pomotroid/projects/1).
2. This has been added the project road map and is planned as a feature. See Issue #2.
3. I would like to keep the scope of the application tight, so I don't anticipate adding a to-do list feature unless there is strong community desire for it.
