### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by maggotrebel** [Splode/pomotroid#5]
Excusme , can i make a new logo for you app ?

**Comment by Splode** [comment]
Sure, I'd be happy to see what you propose 👍

**Comment by maggotrebel** [comment]
Hey brather, this logo done, and this my cotribution , you can check https://utopian.io/utopian-io/@maggotrebel/new-logo-icon-for-pomotroid-open-source-app-confirmed-project-owner

what do you think , i hope you like it. :)

**Comment by Splode** [comment]
Thanks for sharing this, @maggotrebel. Unfortunately, I don't think that the logo you've designed is in line with the spirit of the application. For example, central themes in the application include the circularity of the timer and its distinctive color palette, and visual simplicity. The current logo does a better job of expressing these themes.

However, you've designed a nice logo and the work that you've shared is impressive and thorough. I appreciate your having taken the time to share and contribute. I hope that you use what you've produce in your portfolio.
