### ISSUE TITLE
[Feature request] Data log for statistics

### ISSUE THREAD

**Issue by manastalukdar** [Splode/pomotroid#51]
A data logging feature that can later on be utilized for generating statistics would be great.

**Comment by Splode** [comment]
I suppose it would be fairly trivial to add a logger that writes to the filesystem. What stats would you be interested in seeing?

**Comment by manastalukdar** [comment]
I think at the very least a record of how much time was spent working, and being able to slice that based on time ranges. Additionally, if I have two such data logs from two different machines, being able to merge those logs would be great.

On top of that being able to tag certain "work" and keeping track of logged "work time" by tags would be even better. But this will probably involve changes in the app engine and UI as well.

**Comment by Splode** [comment]
Logging implemented in [v0.10.0](https://github.com/Splode/pomotroid/releases/tag/v0.10.0)
