### ISSUE TITLE
[Feature request] Allow Pomotroid to be installed through Scoop/package managers

### ISSUE THREAD

**Issue by shewlian** [Splode/pomotroid#53]
Not sure if this is a feature or a suggestion, but I'd love to be able to install Pomotroid by typing `scoop install pomotroid` if I have [Scoop](https://github.com/lukesampson/scoop) or any other package manager installed, instead of downloading it from the releases page.

**Comment by Splode** [comment]
You can now install Pomotroid using scoop:

```
scoop install https://raw.githubusercontent.com/Splode/pomotroid/master/pomotroid.json
```

It will install the portable version and will also provide the alias `pomotroid`, so you can start it from the command line. 

It hasn't been added to any public buckets, but may be in the future.

Thanks for the suggestion :+1:

**Comment by redactedscribe** [comment]
It would be great if the project's README also listed Scoop as an available source on Windows as package managers have become more popular on the platform in recent years. Or better yet, submitted to Scoop's Extras bucket.

Looks like WinGet is also a source, although its serving a very outdated version (0.13.0). Unlike Scoop, WinGet requires users to request manifests to be updated for it to serve a new version as far as I recall.
