### ISSUE TITLE
Add a progress bar on windows icon tray

### ISSUE THREAD

**Issue by napstercc** [Splode/pomotroid#58]
It would be nice if the windows icon in the taskbar gets progressively filled as the timer progresses. Also a red progressing bar would be nice to indicate "in pomodoro" and a green progress bar for "in break mode".

**Comment by napstercc** [comment]
[Example here of the app "hourglass which progressively fills up](https://i.imgur.com/FP1h5pM.png)

**Comment by letmaik** [comment]
The tray icon has a dynamic animation already, but I think you rather mean the task bar icon. I much prefer to keep it tiny in the tray icon area than to have it in the task bar. Maybe that works for you too?

**Comment by napstercc** [comment]
@letmaik Nice, I didn't know, it's really practical, thanks!
