### ISSUE TITLE
Show app on screen when work timer is up

### ISSUE THREAD

**Issue by AndyL964** [Splode/pomotroid#64]
The thing with these timers, is that for them to be effective, you need to follow a set schedule. At the same time, however, me or other people may not like to have the timer pinned on screen all the time (plus the fact that it can be distracting to have the timer visible).

**Comment by Splode** [comment]
There are two ancillary methods for alerting users when a timer is up:
1. native notifications
2. alert sounds

Personally, I find windows that unexpectedly force focus to be distracting and annoying.
