### ISSUE TITLE
Export historical data

### ISSUE THREAD

**Issue by espetro** [Splode/pomotroid#70]
Hey @Splode & other contributors,

Congrats for the awesome-yet-simple app you've made! I use it everyday on my college routine. However, I would like to have an option to keep a record of how I've been doing my *pomodoros*, i.e.

  + A record to check how it's been the last 7/14/30 days
  + A way to see which time slots are more productive for me
  + At which hours I'm more used to skip a pomodoro or a break (or how many times a day)

I've never done stuff this big with Vue, but I'm keen to do it myself. Is there any ongoing work for this? If not, where should I start?

**Comment by Splode** [comment]
Hi @espetro, thanks for your interest and contribution.

What you're describing sounds like a combination of logging and data visualization. There isn't a plan for implementing either of these at the moment, but you're more than welcome to tackle either if you're interested.

I think adding a logging mechanism would be the first step and a bit more straightforward. You wouldn't necessarily need much experience with Vue, as it would more likely involve Electron and Nodejs APIs.

**Comment by Splode** [comment]
Logging implemented in [v0.10.0](https://github.com/Splode/pomotroid/releases/tag/v0.10.0)
