### ISSUE TITLE
Timer displays incorrect time during round transition

### ISSUE THREAD

**Issue by Aborres** [Splode/pomotroid#74]
Hey, 

I have been testing the app today for the first time, and it is being great so far (thanks).

However I have noticed this:

Everytime you press play the timer resets to 22:01 before setting its correct time.
When starting a break it resets to -22:01 and then sets itself to whatever you have configured it to do.

![image](https://user-images.githubusercontent.com/9192778/78011533-9ba88a00-733b-11ea-82e1-5548b967e4f6.png)

These are the settings I am using:

![image](https://user-images.githubusercontent.com/9192778/78011790-f641e600-733b-11ea-9b1f-c3f82777aeac.png)

![image](https://user-images.githubusercontent.com/9192778/78011811-022da800-733c-11ea-8a51-9a68190f5f8a.png)

Also, If you accept feedback, it seems like the minimize to tray only works if you restart the app, it would be nice if it were to tell you.

Thanks!

Edit: spelling

**Comment by Aborres** [comment]
Quick Update: the long break one days the same thing but that one turns to -10:01 before setting itself to 15:00

**Comment by Splode** [comment]
Thanks for the detailed issue report @Aborres. I've seen this behavior, too, but haven't tackled it yet. Your documentation of it is helpful, though!

Basically what you're seeing is the difference between the current round time (25) and the next round time (3), which is 22.

Regarding the minimize-to-tray feature, this should happen without having to restart the application, so I think that's a bug. I'll create a separate issue for that based on your findings.

**Comment by Aborres** [comment]
No worries, I can't expect you to start debugging it if you can't see the issue for yourself :) 

I think I have found a good way to replicate this, If you click on the little arrow to advance the clock while the time is running, the next time to press play it will take the curr time in the clock - the time that had passed in the clock before the click on the arrow. 

For example:

Running a 25:00 min long timer.
Click on the arrow at 24:55
3:00 min long break is displayed.
Press play
2:55 min appears for a second and then 3:00 starts the countdown.

**Comment by Splode** [comment]
This issue has been resolved with b7a2419 and is availble on `v0.7.1`.

Thanks again!
