### ISSUE TITLE
Ransomware found inside the downloaded for windows artifact (20200409)

### ISSUE THREAD

**Issue by mazaltod** [Splode/pomotroid#77]
downloaded Windows artifact from your web site. 
The enterprise antivirus found a randsomware. 
Please check.
Thanks

**Comment by Splode** [comment]
Can you provide more information?

I'd be extremely surprised if that were the case. The artifacts are generated on Travis CI's servers and the project's entire source is open.

**Comment by mazaltod** [comment]
I'm not sure to be able to provide the needed information as it could be realted to the network/firefall configuration done  outside my control and knowledge. 
Howerver here is what happends on my laptop 

![image](https://user-images.githubusercontent.com/17778874/78904782-5abc1e00-7a7d-11ea-82ef-c0c43a419fb4.png)

and when I continue (Execution of execution):
![image](https://user-images.githubusercontent.com/17778874/78904871-7b847380-7a7d-11ea-8cd9-7fe9407ed682.png)

![image](https://user-images.githubusercontent.com/17778874/78904901-86d79f00-7a7d-11ea-9254-a0fab599c8a2.png)

May be your are right and it is the antivirus policy that I should request to be changed to my staff. However it is very rare that this happen so may be there is somtething to improve. 
I undestand it is very light and i am sorry not to give more. 
Have a good day. 
Thanks,
David

**Comment by Splode** [comment]
Thanks for the details. My guess is that because Pomotroid does not ship with [code signing](https://en.wikipedia.org/wiki/Code_signing), some anti-virus software will raise an alarm. Unfortunately, as this is a free, hobby project there are no plans to ship with code signing any time soon.

Thanks for contributing!

**Comment by ArnavGautamGit** [comment]
Hey I am also getting the same error on my personal Windows 10 laptop... should I run this without Windows Defender?

<img width="533" height="497" alt="Image" src="https://github.com/user-attachments/assets/85624cba-e2dd-4c67-8e34-2409c7d7a256" />
