### ISSUE TITLE
[Feature request] add tic toc sound option

### ISSUE THREAD

**Issue by authmane512** [Splode/pomotroid#83]
hello,

Could you add a tic toc sound option while timer is running? It is a very important feature for the pomodoro workflow.

Thanks!

**Comment by Splode** [comment]
I like this idea. It would be nice if it was an option, at least. I’ll see about finding a nice tick sound to use.

**Comment by authmane512** [comment]
Thank you.

**Comment by Splode** [comment]
Timer tick sounds implemented in [v0.10.0](https://github.com/Splode/pomotroid/releases/tag/v0.10.0)
