### ISSUE TITLE
Security Warning Mac

### ISSUE THREAD

**Issue by KutnerUri** [Splode/pomotroid#9]
In Mac, we get a warning saying that "Pomotroid can't be opened because it is from an unidentified developer". Please register it with an Apple Store User to increase the sense of security.
<img width="532" alt="screen shot 2018-03-12 at 10 14 15" src="https://user-images.githubusercontent.com/5400361/37272065-259fa822-25de-11e8-9c1e-a3c041d11b55.png">

**Comment by Splode** [comment]
This is a code-signing issue. I haven't code-signed any of the Pomotroid releases, nor do I intend to. Code-signing with Apple costs around ~100/year and as open-source project, I wouldn't be able to recoup this cost. Windows users will encounter a similar message depending on their settings.

You can edit your Mac OS system preferences to open applications from unidentified developers, if you choose.

For more information on Apple code signing, refer to:
- [https://developer.apple.com/support/code-signing/](https://developer.apple.com/support/code-signing/)
- [https://developer.apple.com/support/compare-memberships/](https://developer.apple.com/support/compare-memberships/)

**Comment by KutnerUri** [comment]
Oh my. Yuck.
I thought authoring would be a simpler process, or at least free for open
source.

Maybe just put up a message about it? So it would be clear it's not a bug
or that  someone is trying to do a man in the middle.

בתאריך 12 במרץ 2018 17:00,‏ "Christopher Murphy" <notifications@github.com>
כתב:

**Comment by Splode** [comment]
That's a good suggestion. I'll add a note on installation warnings to the README in the next release.

Thanks!

**Comment by KutnerUri** [comment]
Thanks!

בתאריך 13 במרץ 2018 19:43,‏ "Christopher Murphy" <notifications@github.com>
כתב:
