### ISSUE TITLE
report data session

### ISSUE THREAD

**Issue by DataRobot333** [Splode/pomotroid#91]
it would be awesome if the app allow to extract data or make a report of Pomodoro cycle complete and other kinds of data analysis to the user.

**Comment by Splode** [comment]
I’m working on a logging system, which logs activity to a log file. It will log events, such as round type and start/complete time. Each log entry is JSON-compatible for easy parsing. 

I’m thinking of creating a log file per day. It will only keep the latest 14 log files, so as to not eat up too much disk space. 

There’s a separate error log just for errors.

Anything else you’d like to see included?

**Comment by Splode** [comment]
Logging implemented in [v0.10.0](https://github.com/Splode/pomotroid/releases/tag/v0.10.0)
