### ISSUE TITLE
Snap store version is old and has problems starting

### ISSUE THREAD

**Issue by ijdickinson** [Splode/pomotroid#93]
I'm wondering if you have any official relationship with the version of `pomotroid` in the snap store? If I list the app on snap, I see:

```sh
$ snap search pomotroid
Name       Version  Publisher    Notes  Summary
pomotroid  0.7.0    techalchemy  -      Pomotroid is a simple and visually-pleasing Pomodoro timer.
```

Installing this version does work, but for me it only runs just after `snap install`ing. Thereafter, it fails silently, until I `snap remove` and `snap install` it again. But I also notice that it's version 0.7.0, while the latest release here is 0.9.0

Edited to add: I'm running Ubuntu 19.10

**Comment by Splode** [comment]
Thanks for the info. No, I’m not affiliated with the snap version. It looks like I need to contact the maintainer of that particular package and see if I can coordinate an update with them.

**Comment by Splode** [comment]
Probably related to #87

**Comment by ijdickinson** [comment]
@Splode I think it's possibly a different error (or at least a different manifestation of a possibly common root cause). Either when I'm starting from the dock, or from the terminal, it's a silent failure. No error message that I can find on stderr, or any of syslog, dmesg, etc.

**Comment by AleSprea97** [comment]
Hi, on Discover (the KDE software center) some folks in the reviews speculate the snap version hide some data-mining, I can't say about it, but on my I5 3570k it uses 25% of the CPU and it seems to me a little high for a timer app.

**Comment by fluoridepsychosis** [comment]
The snap store version also seems to be up to something nefarious

**Comment by ijdickinson** [comment]
@Splode If @fluoridepsychosis is right, or there's even a risk of that, that version needs urgently to be yanked from the snap store

**Comment by Splode** [comment]
The snap store version isn't an official package; it's a community package. I just installed it on Ubuntu 19.10 and it is indeed out of date. The latest edge release is `v0.11.1` but `v0.7.0` gets installed.

In a virtual machine with 4 cores, Pomotroid consumes about 3-7% CPU. I don't see it making any network traffic whatsoever. Nevertheless, without looking at the source, it's hard to be positive.

If you're concerned, I suggest:

1. Using an officially maintained version from the releases page (or build from source).
2. Contacting the snap maintainer or Snapcraft.

At the least, I'll contact Dan Ryan (the snap author) and see if they're able to address these issues and concerns.

**Comment by ijdickinson** [comment]
Closing old issue
