### ISSUE TITLE
*SUGGESTION* If Possible Please try to reduce the SIZE and RAM Usage

### ISSUE THREAD

**Issue by fisforfaheem** [Splode/pomotroid#96]
Only if it is possible ,

**Comment by johnjacobkenny** [comment]
Could you please share some stats that you found in your analysis :slightly_smiling_face:

**Comment by fisforfaheem** [comment]
it took over 80MBS or ram for starters@!

**Comment by johnjacobkenny** [comment]
I think this might be a limitation of the electron runtime which we wouldn't be able to optimize out. @Splode what do you think?

**Comment by Splode** [comment]
@johnjacobkenny @fisforfaheem This is really an issue with electron. One of its drawbacks is its resource intensiveness. Unfortunately, there's not much we can do about it at this point.
